name: Dependency Cache Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache dependencies
        id: cache-c0f489f
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-c0f489f

      - name: Install dependencies
        run: npm install

      - name: prime-cache-c0f489f
        run: echo "Cache hit? ${{ steps.cache-c0f489f.outputs.cache-hit }}"
