name: Dependency Cache Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        id: cache-c0f489f
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-c0f489f

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: prime-cache-c0f489f
        run: echo "Cache hit? ${{ steps.cache-c0f489f.outputs.cache-hit }}"
