name: IITM GitHub Action Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 24f2004980@ds.study.iitm.ac.in
        run: echo "Hello, world! GitHub Action is running."

      - name: Show date
        run: date
